#!/bin/bash
set -e

if ! [ -L ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_my" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin my.1password.com chris@kurl.co.uk)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get a273iuq24vhtrmaytpin5h27fy .ssh/id_rsa
onepassword_get 33jymqmjkma2hxy7pvsynghuuy .ssh/meatballs
onepassword_get uk4t6rn7mnbvvchyerkof3r6u4 .ssh/intofilm-lms
onepassword_get 46vrdhmhplmbqsra7uq3zanmti .ssh/intofilm-stage
onepassword_get x7iadlraegg34mtk73ma7l47de .ssh/intofilm-production
onepassword_get xekuky2g2ks5un5qzzfa2ys5g4 .ssh/insecure-deployer 
