#!/bin/bash
set -e

if ! [ -L ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_my" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin)"
  fi
}

if ! command -v aws >/dev/null
then
  echo "Install aws-cli first!" >&2
  exit 1
fi

aws_configure_cli () {
  onepassword_login

  echo "Configuring aws profile ${2}..."

  OLDIFS=$IFS
  IFS=$'\n'

  # This assumes there is a section named "aws-cli" in 1password 
  # The fields should be named to match their value in the aws configure command:
  #   $ aws configure set 1password_label   field
  #   $ aws configure set aws_access_key_id somevalue
  for row in $(op item get $1 --format json | jq ".fields[] | select(.section.label == \"aws-cli\")" | jq -c); do
    _jq() {
      echo ${row} | jq -r ${1}
    }

    aws configure set $(_jq ".label") $(_jq ".value") --profile $2
  done

  IFS=$OLDIFS
}

aws_configure_cli ujptzik5a5frtman4cjikerptu default
aws_configure_cli vvz2emc3xrdjvgdaoqczruhgqu intofilm-master
aws_configure_cli pnfvxet36rbt5byoth5dbvnx7i intofilm-production
aws_configure_cli br4ggiaxkfdjbgff42lmdbbbo4 intofilm-development
aws_configure_cli jsbmt4kb5ves3ol4b2sfrevqyy intofilm-legacy
aws_configure_cli 22hinbuhj5aevcxyzyw5cfruyu aerian-production
aws_configure_cli m2xtm7cexffjnct5qwmrquyduu adventure-films
