#!/bin/bash

PLIST_PATH="$HOME/Library/LaunchAgents/com.1password.SSH_AUTH_SOCK.plist"

PLIST_CONTENT=$(cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.1password.SSH_AUTH_SOCK</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>-c</string>
    <string>/bin/ln -sf $HOME/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock \$SSH_AUTH_SOCK</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
EOF
)

# Check if the launch agent already exists
if [[ -e "$PLIST_PATH" ]]; then
    echo "Launch agent already exists. Updating if necessary..."

    # Check if the content needs updating
    if ! cmp -s "$PLIST_PATH" <(echo "$PLIST_CONTENT"); then
        # Update the launch agent
        echo "Updating launch agent..."
        launchctl unload -w "$PLIST_PATH"
        echo "$PLIST_CONTENT" > "$PLIST_PATH"
        launchctl load -w "$PLIST_PATH"
        echo "Launch agent updated successfully."
    else
        echo "No update needed. Launch agent is already up to date."
    fi
else
    # Create the launch agent
    echo "Creating launch agent..."
    echo "$PLIST_CONTENT" > "$PLIST_PATH"
    launchctl load -w "$PLIST_PATH"
    echo "Launch agent created successfully."
fi